---
title: "realnetdata"
author: "Etienne Côme"
date: "10 septembre 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(greed)
library(future)
plan(multisession)
library(ggplot2)
library(ggpubr)
library(dplyr)
library(Matrix)

set.seed(1234)
```


```{r simsbmmotiv,cache=TRUE,echo=FALSE,message=FALSE,results="hide"}
N=1500
K=15
pi=rep(1/K,K)
lambda  = 0.1
lambda_o = 0.025
Ks=5
mu = bdiag(lapply(1:(K/Ks), function(k){matrix(lambda_o,Ks,Ks)+diag(rep(lambda,Ks))}))+0.001
sbm = rsbm(N,pi,mu)
fit = greed(sbm$x,model=new("sbm"),alg=new("hybrid",pop_size=40))
fit_o = greed:::fit_greed(new("sbm"),list(X=sbm$x),sample(1:20,nrow(sbm$x),replace = TRUE))
fit_perm=fit
perm = sample(1:fit_perm@K)
fit_perm@obs_stats$counts=fit_perm@obs_stats$counts[perm]
fit_perm@obs_stats$x_counts=fit_perm@obs_stats$x_counts[perm,perm]
cl=spectral(sbm$x,15)
fit_sp=greed:::fit_greed(new("sbm"),list(X=sbm$x),cl,type="none")
fit_sp_init=greed(sbm$x,model=new("sbm"),alg=new("seed"))
```



```{r,fig.height=8,fig.width=16,echo=FALSE,fig.cap="Motivating example of the proposed algorithm. Block matrix representation of the solutions (upper row) and cluster node link diagram (bottom row)."}
p1=plot(fit_o)+ggtitle("greedy")
p2=plot(fit_perm)+ggtitle("hybrid")
p3=plot(fit)+ggtitle("hybrid + hierarchical ordering")
p4=plot(fit_o,type='nodelink')+ggtitle("")
p5=plot(fit_perm,type='nodelink')+ggtitle("")
p6=plot(fit,type='nodelink')+ggtitle("")
ggarrange(p1,p2,p3,p4,p5,p6,nrow = 2,ncol=3,common.legend = TRUE,legend="left")
```


```{r realdatadcsbm,cache=TRUE,results="hide"}
data("Blogs")
fit_blogs = greed(Blogs$X,model=new("dcsbm"),alg=new("hybrid",pop_size=40))
data("Books")
fit_books = greed(Books$X,model=new("dcsbm"),alg=new("hybrid",pop_size=40))
data("Football")
fit_foot = greed(Football$X,model=new("dcsbm"),alg=new("hybrid",pop_size=40))
data("Jazz")
fit_jazz = greed(Jazz,model=new("dcsbm"),alg=new("hybrid",pop_size=40))
```


```{r real_graphs, fig.height=16,fig.width=16, echo=FALSE}

p1=plot(fit_blogs)+ggtitle("Blogs")
p2=plot(fit_books)+ggtitle("Books")
p3=plot(fit_foot)+ggtitle("Football")
p4=plot(fit_jazz)+ggtitle("Jazz")

p5=plot(fit_blogs,type='nodelink')+ggtitle("")
p6=plot(fit_books,type='nodelink')+ggtitle("")
p7=plot(fit_foot,type='nodelink')+ggtitle("")
p8=plot(fit_jazz,type='nodelink')+ggtitle("")

p9=plot(fit_blogs,type='tree')+ggtitle("")
p10=plot(fit_books,type='tree')+ggtitle("")
p11=plot(fit_foot,type='tree')+ggtitle("")
p12=plot(fit_jazz,type='tree')+ggtitle("")


p13=plot(cut(fit_blogs,2))+ggtitle("")
p14=plot(cut(fit_books,3))+ggtitle("")
p15=plot(cut(fit_foot,10))+ggtitle("")
p16=plot(cut(fit_jazz,5))+ggtitle("")


ggarrange(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,nrow = 4,ncol=4,common.legend = TRUE)

```


```{r pareto_jazz, fig.height=6,fig.width=8, echo=FALSE}
sol   = fit_books
icl   = c(sol@icl,sapply(sol@path,function(v){v$icl1}))
ggicl = data.frame(icl = icl[length(icl):1], K  = 1:length(icl))
#ggfront= sol@ggtree %>% mutate(x=-H) %>% select(x,K) %>% arrange(x) %>% head(sol@K) %>% left_join(ggicl) %>% mutate(xp=lag(x))
ggfront = merge(sol@ggtree[,c("H","K")],ggicl)
ggfront$x = -ggfront$H
ggfront = ggfront[order(ggfront$x)[1:sol@K],]
ggfront$xp = c(min(ggfront$x)-0.05*diff(range(ggfront$x)), ggfront$x[1:(nrow(ggfront)-1)])
ggfront = ggfront[ggfront$x!=ggfront$xp,]
ggnofront = ggicl %>% anti_join(ggfront)
pareto_front=ggplot2::ggplot()+ggplot2::geom_abline(data=ggicl,ggplot2::aes_(intercept=~icl,slope=~K-1),alpha=0.2)+
ggplot2::geom_abline(data=ggnofront,ggplot2::aes_(intercept=~icl,slope=~K-1),alpha=1,color='red',linetype="dashed")+
ggplot2::geom_point(data=ggfront,ggplot2::aes_(x=~x,y=~icl+x*(K-1)))+
ggplot2::geom_segment(data=ggfront,ggplot2::aes_(x=~x,y=~icl+x*(K-1),xend=~xp,yend=~icl+xp*(K-1)))+
ggplot2::scale_x_continuous(expression(paste("log(",alpha,")")),limits = c(min(ggfront$xp),0))+
ggplot2::ylab("ICL")+
ggplot2::ggtitle(paste0(toupper(sol@model@name)," model with : ",max(sol@cl)," clusters."))+
ggplot2::theme_bw()+ggtitle("Front extracted on the Book network")


pareto_zoom =ggplot2::ggplot()+ggplot2::geom_abline(data=ggicl,ggplot2::aes_(intercept=~icl,slope=~K-1),alpha=0.2)+
ggplot2::geom_abline(data=ggnofront,ggplot2::aes_(intercept=~icl,slope=~K-1),alpha=1,color='red',linetype="dashed")+
ggplot2::geom_point(data=ggfront,ggplot2::aes_(x=~x,y=~icl+x*(K-1)))+
ggplot2::geom_segment(data=ggfront,ggplot2::aes_(x=~x,y=~icl+x*(K-1),xend=~xp,yend=~icl+xp*(K-1)))+
ggplot2::scale_x_continuous(expression(paste("log(",alpha,")")),limits = c(-50,0))+
ggplot2::scale_y_continuous("ICL",limits=c(-3150,-3050))+
ggplot2::theme_bw()

#pareto_front+annotation_custom(ggplot2::ggplotGrob(pareto_zoom),xmin=-375,xmax=-150,ymin=-3300,ymax=-3100)
pareto_front

```

```{r lines_jazz, fig.height=4,fig.width=6, echo=FALSE}
sol   = fit_blogs
icl   = c(sol@icl,sapply(sol@path,function(v){v$icl1}))
ggicl = data.frame(icl = icl[length(icl):1], K  = 1:length(icl))
glarge=ggplot(ggicl)+ggplot2::geom_abline(data=ggicl,ggplot2::aes_(intercept=~icl,slope=~K-1,color=~K),alpha=1)+
ggplot2::scale_x_continuous(expression(paste("log(",alpha,")")),limits = c(-2500,0))+
  ggplot2::scale_color_distiller(palette = "YlOrRd")+
ylim(c(-95000,-84000))+ylab("ICL")+
theme_bw()+xlab(expression(paste("log(",alpha,")")))
glarge
```


```{r realdatacodcsbm,cache=TRUE,results="hide"}
data("Xvlegislature")
fit_pol = greed(Xvlegislature$X,alg=new("hybrid",pop_size=40),K=100)
data("Jazz_full")
Xc=Jazz_full$X[rowSums(Jazz_full$X)>2,]
Xc=Xc[,colSums(Xc)>2]
fit_cojazz = greed(Xc,alg=new("hybrid",pop_size=40),K=60)
```

```{r real_pol, fig.height=6,fig.width=18, echo=FALSE}

p1=plot(fit_pol)+ggtitle("")
p2=plot(cut(fit_pol,26),type='tree')+ggtitle("")
p3=plot(cut(fit_pol,26))+ggtitle("")

ggarrange(p1,p2,p3,nrow = 1,ncol=3,common.legend = TRUE)

```

```{r real_cojazz, fig.height=6,fig.width=12, echo=FALSE}

p1=plot(fit_cojazz)+ggtitle("")
p2=plot(fit_cojazz,type='tree')+ggtitle("")
ggarrange(p1,p2,nrow = 1,ncol=2,common.legend = TRUE)

```

