---
title: "ICL maximisation for discrete latent variable models"
author: "Etienne Côme"
date: "23 mai 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, warning=FALSE,out.extra=FALSE,message=FALSE}
library(greed)
library(Matrix)
library(ggpubr)
library(dplyr)
library(future)
library(knitr)
library(mixtools)
library(xtable)
library(methods)
plan(multisession)
```



```{r simualgmm, cache=TRUE,message=FALSE,results="hide",echo=FALSE}
Nbsim = 100
N = 500
S=matrix(0,N,Nbsim)
Fi=matrix(0,N,Nbsim)
Fi_o=matrix(0,N,Nbsim)
Fi_aic=matrix(0,N,Nbsim)
Fi_bic=matrix(0,N,Nbsim)
Fi_icl=matrix(0,N,Nbsim)
Fi_si=matrix(0,N,Nbsim)
Fi_ms=matrix(0,N,Nbsim)
Xlist = list()
for (s in 1:Nbsim){
  K = 15
  pi = rep(1/K,K)
  d   = 100
  nbv = 10 
  mu = matrix(1,K,d)
  mu[cbind(rep(1:K,each=nbv),as.vector(sapply(1:K,function(k){sample(1:d,nbv)})))]=4
  mm = rmm(N,pi,cbind(mu),rep(50,N))
  S[,s]=mm$cl
  Xlist[[s]]=mm
  fit = greed(mm$x,model=new("mm"),alg = new("hybrid",pop_size=40))
  mm$x
  Fi[,s]=fit@cl
  fit_o = greed:::fit_greed(new("mm"),list(X=mm$x),sample(1:20,nrow(mm$x),replace = TRUE))
  Fi_o[,s] = fit_o@cl 
  sel=multmixmodel.sel(as.matrix(mm$x),1:20)
  Kbic=sel[2,ncol(sel)]
  Kaic=sel[1,ncol(sel)]
  Kicl=sel[4,ncol(sel)]
  sol_bic = multmixEM(as.matrix(mm$x),k=Kbic)
  sol_aic = multmixEM(as.matrix(mm$x),k=Kaic)
  sol_icl = multmixEM(as.matrix(mm$x),k=Kicl)
  Fi_bic[,s] = apply(sol_bic$posterior,1,which.max)
  Fi_aic[,s] = apply(sol_aic$posterior,1,which.max)
  Fi_icl[,s] = apply(sol_icl$posterior,1,which.max)
  fit_sp_init=greed(mm$x,model=new("mm"),alg=new("seed"))
  Fi_si[,s] = fit_sp_init@cl
  fit_ms = greed(mm$x,model=new("mm"),alg = new("multistarts"))
  Fi_ms[,s]=fit_ms@cl
}
```

```{r,echo=FALSE}

iclsim=function(s,cl){
    fit = greed:::fit_greed(new("mm"),list(X=Xlist[[s]]$x),cl,type = "none")
    fit@icl
}

rFi = tibble(alg="Hybrid",nmi=sapply(1:Nbsim,function(s){NMI(Fi[,s],S[,s])}),
             icl=sapply(1:Nbsim,function(s){iclsim(s,Fi[,s])}))
rFi_o = tibble(alg="Greedy",nmi=sapply(1:Nbsim,function(s){NMI(Fi_o[,s],S[,s])}),
               icl=sapply(1:Nbsim,function(s){iclsim(s,Fi_o[,s])}))
rFi_aic = tibble(alg="EM + AIC",nmi=sapply(1:Nbsim,function(s){NMI(Fi_aic[,s],S[,s])}),
                 icl=sapply(1:Nbsim,function(s){iclsim(s,Fi_aic[,s])}))
rFi_bic = tibble(alg="EM + BIC",nmi=sapply(1:Nbsim,function(s){NMI(Fi_bic[,s],S[,s])}),
                 icl=sapply(1:Nbsim,function(s){iclsim(s,Fi_bic[,s])}))
rFi_icl = tibble(alg="EM + ICL",nmi=sapply(1:Nbsim,function(s){NMI(Fi_icl[,s],S[,s])}),
                 icl=sapply(1:Nbsim,function(s){iclsim(s,Fi_icl[,s])}))
rFi_si = tibble(alg="Seed",nmi=sapply(1:Nbsim,function(s){NMI(Fi_si[,s],S[,s])}),
                icl=sapply(1:Nbsim,function(s){iclsim(s,Fi_si[,s])}))
rFi_ms = tibble(alg="Multistart",nmi=sapply(1:Nbsim,function(s){NMI(Fi_ms[,s],S[,s])}),
                icl=sapply(1:Nbsim,function(s){iclsim(s,Fi_ms[,s])}))
resSim = rFi %>% bind_rows(rFi_o) %>% bind_rows(rFi_bic) %>% bind_rows(rFi_aic)%>% bind_rows(rFi_si)%>% bind_rows(rFi_ms) %>% mutate(alg=factor(alg,levels=c("EM + BIC","EM + AIC","Greedy","Multistart","Seed","Hybrid")))
```


```{r mmalgperf,fig.width=10,fig.height=4.5,echo=FALSE, fig.cap="Evolution of the ICL criterion aliong the different generation build by the algorithm (left). comparison in term of NMI with the simulated clusters for several algorithm."}
perf=ggplot(resSim)+geom_boxplot(aes(x=alg,y=nmi,group=alg))+geom_point(aes(x=alg,y=nmi))+xlab("")+ylab("Normalized mutual information")+theme_bw()
perficl=ggplot(resSim)+geom_boxplot(aes(x=alg,y=icl,group=alg))+geom_point(aes(x=alg,y=icl))+xlab("")+ylab("ICL")+theme_bw()
ggarrange(perf,perficl,nrow = 1,ncol = 2)
```

```{r mmscatter,echo=FALSE,fig.width=10,fig.height=4.5}
ggs=tibble(ms=rFi_ms$icl,hybrid=rFi$icl,seed=rFi_si$icl)
ggpms = ggplot()+geom_point(data=ggs,aes(x=ms,y=hybrid))+geom_abline(aes(slope=1,intercept=0),color="red")+theme_bw()+coord_equal()+ylab("ICL - Hybrid")+xlab("ICL Multistart")
ggpsi = ggplot()+geom_point(data=ggs,aes(x=ms,y=seed))+geom_abline(aes(slope=1,intercept=0),color="red")+theme_bw()+coord_equal()+ylab("ICL - Hybrid")+xlab("ICL Seed")
ggarrange(ggpms,ggpsi,nrow=1,ncol=2)
```



```{r mmKbar,echo=FALSE}
rFi = tibble(alg="Hybrid",K=sapply(1:Nbsim,function(s){max(Fi[,s])}))
rFi_o = tibble(alg="Greedy",K=sapply(1:Nbsim,function(s){max(Fi_o[,s])}))
rFi_aic = tibble(alg="EM + AIC",K=sapply(1:Nbsim,function(s){max(Fi_aic[,s])}))
rFi_bic = tibble(alg="EM + BIC",K=sapply(1:Nbsim,function(s){max(Fi_bic[,s])}))
rFi_icl = tibble(alg="EM + ICL",K=sapply(1:Nbsim,function(s){max(Fi_icl[,s])}))
rFi_si = tibble(alg="Seed",K=sapply(1:Nbsim,function(s){max(Fi_si[,s])}))
rFi_ms = tibble(alg="Multistart",K=sapply(1:Nbsim,function(s){max(Fi_ms[,s])}))
resSim = rFi %>% bind_rows(rFi_o) %>% bind_rows(rFi_icl) %>% bind_rows(rFi_bic) %>% bind_rows(rFi_aic)%>% bind_rows(rFi_si)%>% bind_rows(rFi_ms) %>% mutate(alg=factor(alg,levels=c("EM + BIC","EM + AIC","EM + ICL","Greedy","Multistart","Seed","Hybrid")),K=factor(K,levels = 1:20))
ggplot(resSim %>% filter(alg!="EM + ICL"))+geom_bar(aes(x=K),stat = "count")+facet_wrap(~alg)+theme_bw()
```



