---
title: "ICL maximisation for discrete latent variable models"
author: "Etienne Côme"
date: "23 mai 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, warning=FALSE,out.extra=FALSE,message=FALSE}
library(greed)
library(Matrix)
library(ggpubr)
library(dplyr)
library(future)
library(knitr)
library(mixtools)
library(xtable)
plan(multisession)
```


```{r simualgsbm, cache=TRUE,message=FALSE,results="hide",echo=FALSE}

Nbsim = 100
S=matrix(0,1500,Nbsim)
Fi=matrix(0,1500,Nbsim)
Fi_o=matrix(0,1500,Nbsim)
Fi_s=matrix(0,1500,Nbsim)
Fi_si=matrix(0,1500,Nbsim)
Fi_ms=matrix(0,1500,Nbsim)
Xlist = list()
for (s in 1:Nbsim){
  N=1500
  K=15
  pi=rep(1/K,K)
  lambda  = 0.1
  lambda_o = 0.025
  Ks=5
  mu = bdiag(lapply(1:(K/Ks), function(k){matrix(lambda_o,Ks,Ks)+diag(rep(lambda,Ks))}))+0.001
  sbm = rsbm(N,pi,mu)  
  S[,s]=sbm$cl
  Xlist[[s]]=sbm
  fit = greed(sbm$x,model=new("sbm"),alg = new("hybrid",pop_size=50))
  Fi[,s]=fit@cl
  fit_o = greed::fit_greed(new("sbm"),list(X=sbm$x),sample(1:20,nrow(sbm$x),replace = TRUE))
  Fi_o[,s] = fit_o@cl 
  cl=spectral(sbm$x,15)
  Fi_s[,s] = cl 
  fit_sp_init=greed(sbm$x,model=new("sbm"),alg=new("seed"))
  Fi_si[,s] = fit_sp_init@cl
  fit_ms = greed(sbm$x,model=new("sbm"),alg = new("multistarts"))
  Fi_ms[,s]=fit_ms@cl
}
```

```{r}
N=1500
K=15
pi=rep(1/K,K)
lambda  = 0.1
lambda_o = 0.025
Ks=5
mu = bdiag(lapply(1:(K/Ks), function(k){matrix(lambda_o,Ks,Ks)+diag(rep(lambda,Ks))}))+0.001
sbm = rsbm(N,pi,mu)
```

```{r,cache=TRUE,echo=FALSE,message=FALSE,results="hide"}
fit = greed(sbm$x,model=new("sbm"))
```





    
```{r,fig.height=5,fig.width=5,echo=FALSE}
gen=ggplot(fit@train_hist)+geom_boxplot(aes(x=generation,y=icl,group=generation))+geom_point(aes(x=generation,y=icl,group=generation))+
  ggtitle("Evolution of ICL with respect to generations")+
  theme_bw()
#tree=plot(fit,type='tree')+ggtitle("Dendogramme derived from the best solution")
#ggarrange(gen,tree)
#gen
```


```{r,echo=FALSE}
rFi = tibble(alg="Hybrid",nmi=sapply(1:Nbsim,function(s){NMI(Fi[,s],S[,s])}))
rFi_o = tibble(alg="Greedy",nmi=sapply(1:Nbsim,function(s){NMI(Fi_o[,s],S[,s])}))
rFi_s = tibble(alg="Spectral",nmi=sapply(1:Nbsim,function(s){NMI(Fi_s[,s],S[,s])}))
rFi_si = tibble(alg="Seed",nmi=sapply(1:Nbsim,function(s){NMI(Fi_si[,s],S[,s])}))
rFi_ms = tibble(alg="Multistart",nmi=sapply(1:Nbsim,function(s){NMI(Fi_ms[,s],S[,s])}))
resSim = rFi %>% bind_rows(rFi_o) %>% bind_rows(rFi_s)%>% bind_rows(rFi_si)%>% bind_rows(rFi_ms) %>% mutate(alg=factor(alg,levels=c("Greedy","Multistart","Spectral","Seed","Hybrid")))
```


```{r,fig.width=10,fig.height=5,echo=FALSE, fig.cap="Evolution of the ICL criterion aliong the different generation build by the algorithm (left). comparison in term of NMI with the simulated clusters for several algorithm."}
perf=ggplot(resSim)+geom_boxplot(aes(x=alg,y=nmi,group=alg))+geom_point(aes(x=alg,y=nmi))+xlab("")+ylab("Normalized mutual information")+theme_bw()+ggtitle("Algorithms performance comparison")
ggarrange(gen,perf)
```


